name: Reusable Locust Load Test

on:
  workflow_call:
    inputs:
      config:
        required: true
        type: string 
      host:
        required: true
        type: string
      users:
        required: true
        type: number
      spawn_rate:
        required: true
        type: number
      duration:
        required: true
        type: string 
      csv_prefix:
        required: false
        type: string
        default: result

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Locust
        run: pip install locust requests

      - name: Write config.json
        run: |
          echo '${{ inputs.config }}' > config.json
          cat config.json

      - name: Run Locust test
        continue-on-error: true
        run: |
          locust -f locustfile.py \
            --headless \
            -u ${{ inputs.users }} \
            -r ${{ inputs.spawn_rate }} \
            --run-time ${{ inputs.duration }} \
            --host "${{ inputs.host }}" \
            --csv=${{ inputs.csv_prefix }}

      - name: Upload Locust results
        uses: actions/upload-artifact@v4
        with:
          name: locust-results
          path: ${{ inputs.csv_prefix }}_*.csv
