name: Run Locust Test

on:
  workflow_dispatch:

jobs:
  call-load-test:
    uses: ./.github/workflows/locust-loadtest.yml
    with:
      host: 'https://jsonplaceholder.typicode.com'
      users: 10
      spawn_rate: 1
      duration: 10s
      csv_prefix: todo-test
      config: |
        {
          "apis": [
            {
              "url": "/todos/1",
              "method": "GET",
              "assert": {
                "status_code": 300
              }
            },
            {
              "url": "/todos/1",
              "method": "GET",
              "assert": {
                "status_code": 200,
                "body_contains": {
                  "id": 1,
                  "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                  "userId": 1
                }
              }
            },
            {
              "url": "/posts",
              "method": "POST",
              "body": {
                "title": "foo",
                "body": "bar",
                "userId": 1
              },
              "headers": {
                "Content-type": "application/json; charset=UTF-8"
              },
              "assert": {
                "status_code": 201,
                "body_contains": {
                  "id": 101,
                  "title": "foo",
                  "body": "bar",
                  "userId": 1
                }
              }
            }
          ]
        }
